version: "3.9"

services:
  comic-frontend:
    container_name: comic-frontend
    image: comic-frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 2222:2222
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5555
    restart: unless-stopped
    volumes:
      - public:/public
    depends_on:
      - comic-backend

  comic-backend:
    container_name: comic-backend
    image: comic-backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5555:5555
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:4321/comic?schema=public

  db:
    container_name: db
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comic
    ports:
      - 4321:4321
    volumes:
      - pgdata:/var/lib/postgresql/data

  search-engine:
    container_name: search-engine
    image: getmeili/meilisearch:v1.7
    restart: unless-stopped
    environment:
      - MASTERKEY=
    volumes:
      - meili_data:/meili_data

volumes:
  pgdata: {}
  public: {}
  meili_data: {}
